FROM ghcr.io/mark0725/agent-go-docker:latest

ENV DEBIAN_FRONTEND=noninteractive

USER node

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/node/.cargo/bin:${PATH}"

USER root
